import { defineStore } from 'pinia'

export const useMyAppResourceStore = defineStore('myAppResourceStore', {
  state: (): TypeAppResource => ({
    viewportWidth: 0,
    careerHistory: [
      {
        company: "Omniswift",
        role: "Senior Software Engineer",
        duration: "Mar 2025 - present",
        location: "Abuja, Nigeria",
        employmentType: "Full time",
        descriptions: [
          "Developed and maintained mission critical applications for the Nigerian Government.",
          "Ran teams of upwards of 5 developers and provided technical guidance and mentorship.",
          "Increased client retention rates by completely overhauling new website design improving user experience and conversion rates.",
          "Increased consumer satisfaction rates to 80% by developing and maintaining versatile CRM platform for managing customer interactions and data with a return of new projects of ₦1.5 Billion in revenue",
          "Maintained security protocols accross all sites",
        ],
      },
      {
        company: "Tiqwa",
        role: "Senior Software Engineer",
        duration: "Jan 2024 - Feb 2025",
        location: "Abuja, Nigeria",
        employmentType: "Full time",
        descriptions: [
          "Maintained and improved the administrative section of the travel agency for multitenancy for multiple distinct apps.",
          "Increased client retention rate by 100% by improving and rewriting legacy codes, fixing local storage bugs and improving UI/UX of the admin app.",
          "Implemented new styles, animations and JS logic to give an app-like feel to the web apps.",
          "Created, implemented designs, and cross-platform testing of email structures for multiple email templates.",
          "Owned advanced styling, animation, logic, and fetch automation.",
          "Created a plugin widget that introduced a new pricing plan, raising sales and customer base by 30% and 50% respectively and earning over 3M in subscription sales.",
          "Responsible for user- and admin-facing surfaces across app, admin, and emails.",
        ],
      },
      {
        company: "THCO",
        role: "Frontend Engineer",
        employmentType: "Part time",
        duration: "Aug 2023 - Jan 2025",
        location: "Lagos Nigeria",
        descriptions: [
          "Developed and launched the first AI-driven recruitment software, contributing to a net gain of $98,000 in the first month.",
          "Implemented and maintained the AI-driven recruiting platform from inception through production, including key employee search and data management.",
          "Implemented email systems and campaigns to send, manage, and improve the recruiter experience.",
          "Owned advanced styling, animation, logic, and fetch automation.",
          "Improved user feedback management by creating and registering key employees on Agile, boosting efficiency by 75%.",
          "Responsible for user- and admin-facing surfaces across app, admin, and job boards.",
        ],
      },
      {
        company: "Bex-it Digital Solutions",
        role: "Senior Frontend Developer",
        duration: "Feb 2022 - Nov 2024",
        location: "Abuja, Nigeria",
        employmentType: "Full time",
        descriptions: [
          "Developed and maintained software using React, Nuxt, Vue, Laravel, and MySQL.",
          "Collaborated with cross-functional teams, reducing project delivery timelines from about 8 months to 4-5 months.",
          "Improved development efficiency by about 50% through automated testing and SOPs.",
          "Led CMS development.",
          "Engaged clients to clarify goals and requirements.",
          "Increased maintenance client retention by about 95% through solid code structure and engagement.",
        ],
      },
      {
        company: "Chronicles Software",
        role: "Frontend Developer",
        duration: "Jan 2021 - Nov 2021",
        location: "Lagos, Nigeria",
        employmentType: "Contract",
        descriptions: [
          "Developed and maintained applications using React, Next.js, and Redux.",
          "Collaborated with Windows, mobile, and backend teams, shortening Success-box delivery from about 15 months to about 6 months.",
          "Designed test sessions, ticket response automation, and book-reading animations.",
          "Built CMS features for admin, parents, and teachers.",
          "Engaged clients to clarify goals and requirements.",
          "Increased student retention by about 15% through strong animation and smooth transitions.",
        ],
      },
    ],
    techStack: [
      {
        title: "Frontend Development",
        content: [
          "Vue.js",
          "React.js",
          "Next.js",
          "Nuxt.js",
          "Tailwind CSS",
          "HTML",
          "CSS",
          "GSAP",
          "JavaScript",
          "TypeScript",
        ],
      },
      {
        title: "Backend Development",
        content: ["Node.js", "PHP/Laravel", "Express.js", "MongoDB", "MySQL"],
      },
      {
        title: "Database Management",
        content: [
          "MySQL",
          "PostgreSQL",
          "MongoDB",
          "Redis",
          "SQLite",
          "Oracle",
          "SQL Server",
        ],
      },
      {
        title: "DevOps",
        content: [
          "Docker",
          "Kubernetes",
          "CI/CD",
          "Git",
          "GitHub",
          "GitLab",
          "Bitbucket",
        ],
      },
    ],
  }),
  getters: {},
  actions: {}
})
